import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: custom-fields  |  Resource value: wsCustomFields
// 5 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsCustomFieldsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
			},
		},
		options: [
			{
				name: 'Add Update Custom Field',
				value: 'wsAddupdatecustomfield',
				action: 'Add Update Custom Field via Web Services',
				description: 'Add or update a custom field.',
			},
			{
				name: 'Delete Custom Field',
				value: 'wsDeletecustomfield',
				action: 'Delete Custom Field via Web Services',
				description: 'Delete custom fields by Id.',
			},
			{
				name: 'List Custom Fields',
				value: 'wsListcustomfields',
				action: 'List Custom Fields via Web Services',
				description: 'Retrieve details of custom fields for different entities.',
			},
			{
				name: 'Set Contact Custom Field Value',
				value: 'wsSetcontactcustomfieldvalue',
				action: 'Set Contact Custom Field Value via Web Services',
				description: 'Sets the value of a custom field on a contact.',
			},
			{
				name: 'Set Custom Field Value By Field Name',
				value: 'wsSetcustomfieldvaluebyfieldname',
				action: 'Set Custom Field Value By Field Name via Web Services',
				description: 'Sets the value of a custom field on a contact.',
			},
		],
		default: 'wsAddupdatecustomfield',
	},
];

export const wsCustomFieldsFields: INodeProperties[] = [
	{
		displayName: 'Entity Type',
		name: 'entityType',
		type: 'string',
		required: true,
		default: '',
		description: 'Not Mandatory if WebUser Custom Field.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsAddupdatecustomfield'],
			},
		},
	},
	{
		displayName: 'Caption',
		name: 'caption',
		type: 'string',
		required: true,
		default: '',
		description: 'Caption of the custom field.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsAddupdatecustomfield'],
			},
		},
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'string',
		required: true,
		default: '',
		description: 'Custom field type.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsAddupdatecustomfield'],
			},
		},
	},
	{
		displayName: 'Entity Group Id',
		name: 'entityGroupId',
		type: 'number',
		required: true,
		default: 0,
		description: '',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsAddupdatecustomfield'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsAddupdatecustomfield'],
			},
		},
		options: [
			{
				displayName: 'Extra',
				name: 'extra',
				type: 'string',
				default: '',
				description: '',
			},
			{
				displayName: 'Mandatory',
				name: 'mandatory',
				type: 'boolean',
				default: false,
				description: 'Set to 1 if an value is required.',
			},
			{
				displayName: 'Options',
				name: 'options',
				type: 'number',
				default: 0,
				description: '',
			},
			{
				displayName: 'Default Value',
				name: 'defaultValue',
				type: 'string',
				default: '',
				description: 'Set the default value.',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'Set order of custom fields.',
			},
			{
				displayName: 'Custom Field Id',
				name: 'customFieldId',
				type: 'number',
				default: 0,
				description: 'Supply Id to update existing custom field.',
			},
			{
				displayName: 'Mandatory Value',
				name: 'mandatoryValue',
				type: 'string',
				default: '',
				description: '',
			},
			{
				displayName: 'Mandatory Value Alert',
				name: 'mandatoryValueAlert',
				type: 'string',
				default: '',
				description: '',
			},
		],
	},
	{
		displayName: 'Customfield Id',
		name: 'customfieldId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The Id of the custom field to be deleted.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsDeletecustomfield'],
			},
		},
	},
	{
		displayName: 'Entity Type Id',
		name: 'entityTypeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'This parameter selects an entity (ie Contact).',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsListcustomfields'],
			},
		},
	},
	{
		displayName: 'Entity Group Id',
		name: 'entityGroupId',
		type: 'number',
		required: true,
		default: 0,
		description: 'This parameter specifies the actual "group" of custom fields. See note.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsListcustomfields'],
			},
		},
	},
	{
		displayName: 'cust_custom field name',
		name: 'cust_custom field name',
		type: 'string',
		required: true,
		default: '',
		description: 'Pass cust_ followed by the caption of an existing custom field.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcontactcustomfieldvalue'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcontactcustomfieldvalue'],
			},
		},
		options: [
			{
				displayName: 'Contact Id',
				name: 'contactId',
				type: 'number',
				default: 0,
				description: 'Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Contact Ref',
				name: 'contactRef',
				type: 'string',
				default: '',
				description: 'Provide either ContactId or ContactRef.',
			},
		],
	},
	{
		displayName: 'Entity Id',
		name: 'entityId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of the entity.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcustomfieldvaluebyfieldname'],
			},
		},
	},
	{
		displayName: 'Entity Type Id',
		name: 'entityTypeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of entity type, Contact = 1, Contact Note = 2, Job = 3.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcustomfieldvaluebyfieldname'],
			},
		},
	},
	{
		displayName: 'Custom Field Name',
		name: 'customFieldName',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of custom field.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcustomfieldvaluebyfieldname'],
			},
		},
	},
	{
		displayName: 'Custom Field Value',
		name: 'customFieldValue',
		type: 'string',
		required: true,
		default: '',
		description: 'Value to set on custom field.',
		displayOptions: {
			show: {
				resource: ['wsCustomFields'],
				operation: ['wsSetcustomfieldvaluebyfieldname'],
			},
		},
	},
];

export const wsCustomFieldsRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsAddupdatecustomfield': { path: '/custom-fields/addupdatecustomfield', method: 'post', params: [{"camelName":"entityType","apiName":"EntityType","type":"string","default":""},{"camelName":"caption","apiName":"Caption","type":"string","default":""},{"camelName":"type","apiName":"Type","type":"string","default":""},{"camelName":"entityGroupId","apiName":"EntityGroupId","type":"number","default":0},{"camelName":"extra","apiName":"Extra","type":"string","default":""},{"camelName":"mandatory","apiName":"Mandatory","type":"boolean","default":false},{"camelName":"options","apiName":"Options","type":"number","default":0},{"camelName":"defaultValue","apiName":"DefaultValue","type":"string","default":""},{"camelName":"order","apiName":"Order","type":"string","default":""},{"camelName":"customFieldId","apiName":"CustomFieldId","type":"number","default":0},{"camelName":"mandatoryValue","apiName":"MandatoryValue","type":"string","default":""},{"camelName":"mandatoryValueAlert","apiName":"MandatoryValueAlert","type":"string","default":""}] },
	'wsDeletecustomfield': { path: '/custom-fields/deletecustomfield', method: 'post', params: [{"camelName":"customfieldId","apiName":"CustomfieldId","type":"number","default":0}] },
	'wsListcustomfields': { path: '/custom-fields/listcustomfields', method: 'get', params: [{"camelName":"entityTypeId","apiName":"EntityTypeId","type":"number","default":0},{"camelName":"entityGroupId","apiName":"EntityGroupId","type":"number","default":0}] },
	'wsSetcontactcustomfieldvalue': { path: '/custom-fields/setcontactcustomfieldvalue', method: 'post', params: [{"camelName":"contactId","apiName":"ContactId","type":"number","default":0},{"camelName":"contactRef","apiName":"ContactRef","type":"string","default":""},{"camelName":"cust_custom field name","apiName":"cust_custom field name","type":"string","default":""}] },
	'wsSetcustomfieldvaluebyfieldname': { path: '/custom-fields/setcustomfieldvaluebyfieldname', method: 'post', params: [{"camelName":"entityId","apiName":"EntityId","type":"number","default":0},{"camelName":"entityTypeId","apiName":"EntityTypeId","type":"number","default":0},{"camelName":"customFieldName","apiName":"CustomFieldName","type":"string","default":""},{"camelName":"customFieldValue","apiName":"CustomFieldValue","type":"string","default":""}] },
};