import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: reports  |  Resource value: wsReports
// 6 operations generated (standalone). wsReport (binary response) excluded.
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsReportsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsReports'],
			},
		},
		options: [
			{
				name: 'Driver Infringement Events for a Date Range',
				value: 'wsReportdriverinfringement',
				action: 'Driver infringement events for a date range via web services',
				description: 'Returns the same dataset used by the Driver Infringement Report, allowing you to extract each driving infringement event',
			},
			{
				name: 'Driver Performance Data for a Date Range',
				value: 'wsReportdriverperformance',
				action: 'Driver performance data for a date range via web services',
				description: 'This webservice returns the same dataset used by the Driver Performance Report allowing you to extract each data around how your resources drive',
			},
			{
				name: 'Get a List of Reports',
				value: 'wsReportlist',
				action: 'Get a list of reports via web services',
				description: 'BigChange Web Services ReportList: get a list of reports',
			},
			{
				name: 'List Document Templates',
				value: 'wsTemplatelist',
				action: 'List document templates via web services',
				description: 'This service returns a detailed list of the report templates available in BigChange',
			},
			{
				name: 'Vehicle Infringement Events',
				value: 'wsReportvehicleinfringement',
				action: 'Vehicle infringement events via web services',
				description: 'BigChange Web Services ReportVehicleInfringement: vehicle infringement events',
			},
			{
				name: 'Vehicle Performance Data',
				value: 'wsReportvehicleperformance',
				action: 'Vehicle performance data via web services',
				description: 'This service allows you to view how your assets drive. This works like the \'Driver Behaviour\' report to relay the same information, but for assets instead of resources.',
			},
		],
		default: 'wsReportdriverinfringement',
	},
];

export const wsReportsFields: INodeProperties[] = [
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'From Date Range - e.g ‘2024-01-15 09:00:00.000’',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverinfringement'],
			},
		},
	},
	{
		displayName: 'To',
		name: 'to',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'To Date Range - e.g ‘2024-01-15 11:30:00.000’',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverinfringement'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverinfringement'],
			},
		},
		options: [
			{
				displayName: 'Resource Group ID',
				name: 'resourceGroupId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the resource group',
			},
			{
				displayName: 'Resource Group Name',
				name: 'resourceGroupName',
				type: 'string',
				default: '',
				description: 'The group name of the resource',
			},
			{
				displayName: 'Resource ID',
				name: 'resourceId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the resource.. Provide either ResourceId or ResourceReference.',
			},
			{
				displayName: 'Resource Reference',
				name: 'resourceReference',
				type: 'string',
				default: '',
				description: 'The internal textual reference used for the resource.. Provide either ResourceId or ResourceReference.',
			},
			{
				displayName: 'Speed Threshold',
				name: 'speedThreshold',
				type: 'number',
				default: 0,
				description: 'Percentage threshold percentage over the speed limit which triggers an infringement.The default is taken from the speed threshold set on your site',
			},
		],
	},
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'From Date Range - e.g ‘2024-01-15 09:00:00.000’',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverperformance'],
			},
		},
	},
	{
		displayName: 'To',
		name: 'to',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'To Date Range - e.g ‘2024-01-15 11:30:00.000’',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverperformance'],
			},
		},
	},
	{
		displayName: 'Data To Display',
		name: 'dataToDisplay',
		type: 'string',
		required: true,
		default: '',
		description: 'Show data based on:1 = Score2 = Average3 = Occurrences',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverperformance'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportdriverperformance'],
			},
		},
		options: [
			{
				displayName: 'Resource Group Name',
				name: 'resourceGroupName',
				type: 'string',
				default: '',
				description: 'The group name of the resource',
			},
			{
				displayName: 'Resource Group ID',
				name: 'resourceGroupId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the resource group',
			},
			{
				displayName: 'Resource Reference',
				name: 'resourceReference',
				type: 'string',
				default: '',
				description: 'The internal textual reference used for the resource.. Provide either ResourceId or ResourceReference.',
			},
			{
				displayName: 'Resource ID',
				name: 'resourceId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the resource.. Provide either ResourceId or ResourceReference.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsTemplatelist'],
			},
		},
		options: [
			{
				displayName: 'Format',
				name: 'format',
				type: 'number',
				default: 0,
				description: 'Selects which format type list is to be returned',
			},
			{
				displayName: 'Usage Type',
				name: 'usageType',
				type: 'number',
				default: 0,
				description: 'Filters templates list by usage type',
			},
			{
				displayName: 'Abbreviated',
				name: 'abbreviated',
				type: 'boolean',
				default: false,
				description: 'Whether to hide extra template fields such as LetterFooterHeight',
			},
		],
	},
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportvehicleinfringement'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportvehicleinfringement'],
			},
		},
		options: [
			{
				displayName: 'Asset Group ID',
				name: 'assetGroupId',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Asset Group Name',
				name: 'assetGroupName',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Asset ID',
				name: 'assetId',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Asset Registration',
				name: 'assetRegistration',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Include IDs',
				name: 'includeIds',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Include Private',
				name: 'includePrivate',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Include Unknown Registrations',
				name: 'includeUnknownRegistrations',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Speed Threshold',
				name: 'speedThreshold',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'To',
				name: 'to',
				type: 'dateTime',
				default: '',
			},
		],
	},
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'From Date Range - e.g ‘2024-01-15 09:00:00.000’',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportvehicleperformance'],
			},
		},
	},
	{
		displayName: 'Data To Display',
		name: 'dataToDisplay',
		type: 'string',
		required: true,
		default: '',
		description: 'Show data based on:1 = Score2 = Average3 = Occurrences',
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportvehicleperformance'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsReports'],
				operation: ['wsReportvehicleperformance'],
			},
		},
		options: [
			{
				displayName: 'To',
				name: 'to',
				type: 'dateTime',
				default: '',
				description: 'To Date Range - e.g ‘2024-01-15 11:30:00.000’',
			},
			{
				displayName: 'Asset Registration',
				name: 'assetRegistration',
				type: 'string',
				default: '',
				description: 'The registration number of the asset',
			},
			{
				displayName: 'Asset ID',
				name: 'assetId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the asset which can be retrieved using Asset List',
			},
			{
				displayName: 'Asset Type',
				name: 'assetType',
				type: 'string',
				default: '',
				description: 'Asset Type4 = Car5 = Trailer6 = Bus7 = Emergency8 = GoodsLess7_5T9 = GoodsMore7_5T10 = BusLess12',
			},
		],
	},
];

export const wsReportsRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsReportdriverinfringement': { path: '/reports/reportdriverinfringement', method: 'get', params: [{"camelName":"from","apiName":"From","type":"dateTime","default":""},{"camelName":"to","apiName":"To","type":"dateTime","default":""},{"camelName":"resourceGroupName","apiName":"ResourceGroupName","type":"string","default":""},{"camelName":"resourceGroupId","apiName":"ResourceGroupId","type":"number","default":0},{"camelName":"resourceReference","apiName":"ResourceReference","type":"string","default":""},{"camelName":"resourceId","apiName":"ResourceId","type":"number","default":0},{"camelName":"speedThreshold","apiName":"SpeedThreshold","type":"number","default":0}] },
	'wsReportdriverperformance': { path: '/reports/reportdriverperformance', method: 'get', params: [{"camelName":"from","apiName":"From","type":"dateTime","default":""},{"camelName":"to","apiName":"To","type":"dateTime","default":""},{"camelName":"dataToDisplay","apiName":"DataToDisplay","type":"string","default":""},{"camelName":"resourceGroupName","apiName":"ResourceGroupName","type":"string","default":""},{"camelName":"resourceGroupId","apiName":"ResourceGroupId","type":"number","default":0},{"camelName":"resourceReference","apiName":"ResourceReference","type":"string","default":""},{"camelName":"resourceId","apiName":"ResourceId","type":"number","default":0}] },
	'wsReportlist': { path: '/reports/reportlist', method: 'get', params: [] },
	'wsTemplatelist': { path: '/reports/templatelist', method: 'get', params: [{"camelName":"format","apiName":"Format","type":"number","default":0},{"camelName":"usageType","apiName":"UsageType","type":"number","default":0},{"camelName":"abbreviated","apiName":"Abbreviated","type":"boolean","default":false}] },
	'wsReportvehicleinfringement': { path: '/reports/reportvehicleinfringement', method: 'get', params: [{"camelName":"from","apiName":"From","type":"dateTime","default":""},{"camelName":"to","apiName":"To","type":"dateTime","default":""},{"camelName":"speedThreshold","apiName":"SpeedThreshold","type":"number","default":0},{"camelName":"includeIds","apiName":"IncludeIds","type":"boolean","default":false},{"camelName":"includeUnknownRegistrations","apiName":"IncludeUnknownRegistrations","type":"boolean","default":false},{"camelName":"includePrivate","apiName":"IncludePrivate","type":"boolean","default":false},{"camelName":"assetRegistration","apiName":"AssetRegistration","type":"string","default":""},{"camelName":"assetId","apiName":"AssetId","type":"number","default":0},{"camelName":"assetGroupName","apiName":"AssetGroupName","type":"string","default":""},{"camelName":"assetGroupId","apiName":"AssetGroupId","type":"number","default":0}] },
	'wsReportvehicleperformance': { path: '/reports/reportvehicleperformance', method: 'get', params: [{"camelName":"from","apiName":"From","type":"dateTime","default":""},{"camelName":"to","apiName":"To","type":"dateTime","default":""},{"camelName":"dataToDisplay","apiName":"DataToDisplay","type":"string","default":""},{"camelName":"assetRegistration","apiName":"AssetRegistration","type":"string","default":""},{"camelName":"assetId","apiName":"AssetId","type":"number","default":0},{"camelName":"assetType","apiName":"AssetType","type":"string","default":""}] },
};
