import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: worksheets  |  Resource value: wsWorksheets
// 1 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsWorksheetsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsWorksheets'],
			},
		},
		options: [
			{
				name: 'Worksheets And Questions',
				value: 'wsWorksheetsandquestions',
				action: 'Worksheets And Questions via Web Services',
				description: 'This service lists all questions and their associated worksheets, useful when building a spreadsheet to filter by worksheet if csv format is returned.',
			},
		],
		default: 'wsWorksheetsandquestions',
	},
];

export const wsWorksheetsFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsWorksheets'],
				operation: ['wsWorksheetsandquestions'],
			},
		},
		options: [
			{
				displayName: 'Format',
				name: 'format',
				type: 'string',
				default: '',
				description: 'JSON, XML or CSV - default format is JSON.',
			},
		],
	},
];

export const wsWorksheetsRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsWorksheetsandquestions': { path: '/worksheets/worksheetsandquestions', method: 'get', params: [{"camelName":"format","apiName":"Format","type":"string","default":""}] },
};