import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: expenses  |  Resource value: wsExpenses
// 5 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsExpensesOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
			},
		},
		options: [
			{
				name: 'Add or Update an Expense',
				value: 'wsExpensesave',
				action: 'Add or Update an Expense via Web Services',
				description: 'This service allows you to add or update expenses and expense items.',
			},
			{
				name: 'Expense Types',
				value: 'wsExpensetypes',
				action: 'Expense Types via Web Services',
				description: 'This service lists the valid expense types available.',
			},
			{
				name: 'Get a List of Expense Item Statuses',
				value: 'wsExpenseitemstatus',
				action: 'Get a List of Expense Item Statuses via Web Services',
				description: 'This service lists the valid expense statuses available.',
			},
			{
				name: 'Get a List of Expenses',
				value: 'wsExpensesList',
				action: 'Get a List of Expenses via Web Services',
				description: 'Get a List of Expenses.',
			},
			{
				name: 'Remove an Expense',
				value: 'wsExpensedelete',
				action: 'Remove an Expense via Web Services',
				description: 'Destructive — This service deletes the specified expense together with any associated Expense Items.',
			},
		],
		default: 'wsExpensesave',
	},
];

export const wsExpensesFields: INodeProperties[] = [
	{
		displayName: 'Resource Id',
		name: 'resourceId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Unique Id of the resource.',
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesave'],
			},
		},
	},
	{
		displayName: 'Expense Item Currency',
		name: 'expenseItemCurrency',
		type: 'string',
		required: true,
		default: '',
		description: 'ISO 3 character currency identifier E.g.: "GBP" "USD" "EUR" .',
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesave'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesave'],
			},
		},
		options: [
			{
				displayName: 'Expense Id',
				name: 'expenseId',
				type: 'number',
				default: 0,
				description: 'Unique Id of the expense.',
			},
			{
				displayName: 'Start',
				name: 'start',
				type: 'dateTime',
				default: '',
				description: 'Start date and time for expense record e.g. ‘2020-01-09 01:00:00.000’.',
			},
			{
				displayName: 'End',
				name: 'end',
				type: 'dateTime',
				default: '',
				description: 'End date and time for expense record e.g. ‘2020-01-09 23:00:00.000’.',
			},
			{
				displayName: 'Expense Item Id',
				name: 'expenseItemId',
				type: 'number',
				default: 0,
				description: 'Unique Id of the expense item.',
			},
			{
				displayName: 'Expense Item Date',
				name: 'expenseItemDate',
				type: 'dateTime',
				default: '',
				description: 'Date of expense item e.g. ‘2020-01-09 23:00:00.000’.',
			},
			{
				displayName: 'Expense Item Type Id',
				name: 'expenseItemTypeId',
				type: 'number',
				default: 0,
				description: 'Unique Id of the expense item type.',
			},
			{
				displayName: 'Expense Item Excl Tax',
				name: 'expenseItemExclTax',
				type: 'number',
				default: 0,
				description: 'Expense item value prior to tax. These values are used, no calculation is undertaken.',
			},
			{
				displayName: 'Expense Item Incl Tax',
				name: 'expenseItemInclTax',
				type: 'number',
				default: 0,
				description: 'Expense item value prior after tax. These values are used, no calculation is undertaken.',
			},
			{
				displayName: 'Expense Item VAT',
				name: 'expenseItemVAT',
				type: 'number',
				default: 0,
				description: 'Expense item tax amount. These values are used, no calculation is undertaken.',
			},
			{
				displayName: 'Expense Item Fuel',
				name: 'expenseItemFuel',
				type: 'number',
				default: 0,
				description: 'Fuel Cost amount.',
			},
			{
				displayName: 'Expense Item Status',
				name: 'expenseItemStatus',
				type: 'number',
				default: 0,
				description: 'The required expense item status value.',
			},
			{
				displayName: 'Expense Item Comment',
				name: 'expenseItemComment',
				type: 'string',
				default: '',
				description: 'Expense Back Office Comment',
			},
			{
				displayName: 'Is Local Time',
				name: 'isLocalTime',
				type: 'boolean',
				default: false,
				description: 'Set to true when local time is provided, as opposed to a UTC datetime. Default is false.',
			},
		],
	},
	{
		displayName: 'Start',
		name: 'start',
		type: 'string',
		required: true,
		default: '',
		description: '',
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesList'],
			},
		},
	},
	{
		displayName: 'End',
		name: 'end',
		type: 'string',
		required: true,
		default: '',
		description: '',
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesList'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensesList'],
			},
		},
		options: [
			{
				displayName: 'Resource Id',
				name: 'resourceId',
				type: 'number',
				default: 0,
				description: '',
			},
			{
				displayName: 'Item Status Id',
				name: 'itemStatusId',
				type: 'number',
				default: 0,
				description: '',
			},
		],
	},
	{
		displayName: 'Expense Id',
		name: 'expenseId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Unique Id of the expense to remove.',
		displayOptions: {
			show: {
				resource: ['wsExpenses'],
				operation: ['wsExpensedelete'],
			},
		},
	},
];

export const wsExpensesRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsExpensesave': { path: '/expenses/expensesave', method: 'post', params: [{"camelName":"expenseId","apiName":"ExpenseId","type":"number","default":0},{"camelName":"start","apiName":"Start","type":"dateTime","default":""},{"camelName":"end","apiName":"End","type":"dateTime","default":""},{"camelName":"resourceId","apiName":"ResourceId","type":"number","default":0},{"camelName":"expenseItemId","apiName":"ExpenseItemId","type":"number","default":0},{"camelName":"expenseItemDate","apiName":"ExpenseItemDate","type":"dateTime","default":""},{"camelName":"expenseItemTypeId","apiName":"ExpenseItemTypeId","type":"number","default":0},{"camelName":"expenseItemExclTax","apiName":"ExpenseItemExclTax","type":"number","default":0},{"camelName":"expenseItemInclTax","apiName":"ExpenseItemInclTax","type":"number","default":0},{"camelName":"expenseItemVAT","apiName":"ExpenseItemVAT","type":"number","default":0},{"camelName":"expenseItemCurrency","apiName":"ExpenseItemCurrency","type":"string","default":""},{"camelName":"expenseItemFuel","apiName":"ExpenseItemFuel","type":"number","default":0},{"camelName":"expenseItemStatus","apiName":"ExpenseItemStatus","type":"number","default":0},{"camelName":"expenseItemComment","apiName":"ExpenseItemComment","type":"string","default":""},{"camelName":"isLocalTime","apiName":"IsLocalTime","type":"boolean","default":false}] },
	'wsExpensetypes': { path: '/expenses/expensetypes', method: 'get', params: [] },
	'wsExpenseitemstatus': { path: '/expenses/expenseitemstatus', method: 'get', params: [] },
	'wsExpensesList': { path: '/expenses', method: 'get', params: [{"camelName":"start","apiName":"Start","type":"string","default":""},{"camelName":"end","apiName":"End","type":"string","default":""},{"camelName":"resourceId","apiName":"ResourceId","type":"number","default":0},{"camelName":"itemStatusId","apiName":"ItemStatusId","type":"number","default":0}] },
	'wsExpensedelete': { path: '/expenses/expensedelete', method: 'post', params: [{"camelName":"expenseId","apiName":"ExpenseId","type":"number","default":0}] },
};