import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: routes  |  Resource value: wsRoutes
// 6 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsRoutesOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
			},
		},
		options: [
			{
				name: 'Add a Stop to a Route',
				value: 'wsRouteaddstop',
				action: 'Add a Stop to a Route via Web Services',
				description: 'Adds a new stop to the end of a route.',
			},
			{
				name: 'Add or Update a Route',
				value: 'wsRoutesave',
				action: 'Add or Update a Route via Web Services',
				description: 'Adds a new route or updates an existing route.',
			},
			{
				name: 'Get a List of Route Stops',
				value: 'wsRoutestops',
				action: 'Get a List of Route Stops via Web Services',
				description: 'List all the stops on an existing route.',
			},
			{
				name: 'Get a List of Routes',
				value: 'wsRoutesList',
				action: 'Get a List of Routes via Web Services',
				description: 'Get a List of Routes.',
			},
			{
				name: 'Remove a Route',
				value: 'wsRoutedelete',
				action: 'Remove a Route via Web Services',
				description: 'Destructive — Deletes an existing route.',
			},
			{
				name: 'Remove a Stop from a Route',
				value: 'wsRoutedeletestop',
				action: 'Remove a Stop from a Route via Web Services',
				description: 'Destructive — Deletes a stop from the route.',
			},
		],
		default: 'wsRouteaddstop',
	},
];

export const wsRoutesFields: INodeProperties[] = [
	{
		displayName: 'Route Id',
		name: 'routeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of the route to edit Get a list of routes using Route List',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRouteaddstop'],
			},
		},
	},
	{
		displayName: 'Job Type Id',
		name: 'jobTypeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of a job type for the stop being added to the route. Either JobTypeId or JobTypeName required.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRouteaddstop'],
			},
		},
	},
	{
		displayName: 'Job Type Name',
		name: 'jobTypeName',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the job type for the stop being added to the route. Either JobTypeId or JobTypeName required.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRouteaddstop'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRouteaddstop'],
			},
		},
		options: [
			{
				displayName: 'Contact Id',
				name: 'contactId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact which can be retrieved using Contact List. Either ContactId or ContactRef required.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Contact Ref',
				name: 'contactRef',
				type: 'string',
				default: '',
				description: 'The unique identifier of the contact which can be retrieved using Contact List. Either ContactId or ContactRef required.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Stop Dur',
				name: 'stopDur',
				type: 'number',
				default: 0,
				description: 'Job/stop duration in minutes - Defaults to 15 if omitted',
			},
			{
				displayName: 'Stop Time',
				name: 'stopTime',
				type: 'string',
				default: '',
				description: 'Time of day to schedule the job - Format "HH:MM:SS" – 24 hour',
			},
			{
				displayName: 'Stop Description',
				name: 'stopDescription',
				type: 'string',
				default: '',
				description: 'Description of the stop/job - Will appear as the job description when scheduled',
			},
		],
	},
	{
		displayName: 'Route Id',
		name: 'routeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of an existing route. If omitted a new route will be created.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutesave'],
			},
		},
	},
	{
		displayName: 'Route Name',
		name: 'routeName',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the route.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutesave'],
			},
		},
	},
	{
		displayName: 'Route Id',
		name: 'routeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The Id of the route Id for which the Stops are to be returned.  Get a list of routes using Route List',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutestops'],
			},
		},
	},
	{
		displayName: 'Route Id',
		name: 'routeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of the route to delete',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutedelete'],
			},
		},
	},
	{
		displayName: 'Route Id',
		name: 'routeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of the route to edit.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutedeletestop'],
			},
		},
	},
	{
		displayName: 'Stop Id',
		name: 'stopId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Id of stop to remove.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutedeletestop'],
			},
		},
	},
	{
		displayName: 'Stop Num',
		name: 'stopNum',
		type: 'number',
		required: true,
		default: 0,
		description: 'Number of stop to remove.',
		displayOptions: {
			show: {
				resource: ['wsRoutes'],
				operation: ['wsRoutedeletestop'],
			},
		},
	},
];

export const wsRoutesRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsRouteaddstop': { path: '/routes/routeaddstop', method: 'post', params: [{"camelName":"routeId","apiName":"RouteId","type":"number","default":0},{"camelName":"contactId","apiName":"ContactId","type":"number","default":0},{"camelName":"contactRef","apiName":"ContactRef","type":"string","default":""},{"camelName":"jobTypeId","apiName":"JobTypeId","type":"number","default":0},{"camelName":"jobTypeName","apiName":"JobTypeName","type":"string","default":""},{"camelName":"stopDur","apiName":"StopDur","type":"number","default":0},{"camelName":"stopTime","apiName":"StopTime","type":"string","default":""},{"camelName":"stopDescription","apiName":"StopDescription","type":"string","default":""}] },
	'wsRoutesave': { path: '/routes/routesave', method: 'post', params: [{"camelName":"routeId","apiName":"RouteId","type":"number","default":0},{"camelName":"routeName","apiName":"RouteName","type":"string","default":""}] },
	'wsRoutestops': { path: '/routes/routestops', method: 'get', params: [{"camelName":"routeId","apiName":"RouteId","type":"number","default":0}] },
	'wsRoutesList': { path: '/routes', method: 'get', params: [] },
	'wsRoutedelete': { path: '/routes/routedelete', method: 'post', params: [{"camelName":"routeId","apiName":"RouteId","type":"number","default":0}] },
	'wsRoutedeletestop': { path: '/routes/routedeletestop', method: 'post', params: [{"camelName":"routeId","apiName":"RouteId","type":"number","default":0},{"camelName":"stopId","apiName":"StopId","type":"number","default":0},{"camelName":"stopNum","apiName":"StopNum","type":"number","default":0}] },
};