import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: web-users  |  Resource value: wsWebUsers
// 5 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsWebUsersOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
			},
		},
		options: [
			{
				name: 'Add or update a web user',
				value: 'wsWebusersave',
				action: 'Add or update a web user via Web Services',
				description: 'Add or update a web user, by email address.',
			},
			{
				name: 'List user groups',
				value: 'wsUsergroups',
				action: 'List user groups via Web Services',
				description: 'This service lists all of the current user groups.',
			},
			{
				name: 'List web users',
				value: 'wsWebuserlist',
				action: 'List web users via Web Services',
				description: 'Returns a list of all web users accessible by the current user.',
			},
			{
				name: 'Remove a web user by email',
				value: 'wsWebuserdelete',
				action: 'Remove a web user by email via Web Services',
				description: 'Deletes a web user by email address.',
			},
			{
				name: 'User Roles',
				value: 'wsUserroles',
				action: 'User Roles via Web Services',
				description: 'This service lists all of the current user roles.',
			},
		],
		default: 'wsWebusersave',
	},
];

export const wsWebUsersFields: INodeProperties[] = [
	{
		displayName: 'Web User Name',
		name: 'webUserName',
		type: 'string',
		required: true,
		default: '',
		description: 'User name.',
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebusersave'],
			},
		},
	},
	{
		displayName: 'Web User Email',
		name: 'webUserEmail',
		type: 'string',
		required: true,
		default: '',
		description: 'User email.',
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebusersave'],
			},
		},
	},
	{
		displayName: 'Web User Pwd',
		name: 'webUserPwd',
		type: 'string',
		required: true,
		default: '',
		description: 'User password.',
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebusersave'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebusersave'],
			},
		},
		options: [
			{
				displayName: 'User Mobile',
				name: 'userMobile',
				type: 'string',
				default: '',
				description: 'User mobile number.',
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'string',
				default: '',
				description: 'User position.',
			},
			{
				displayName: 'User IP Restriction',
				name: 'userIPRestriction',
				type: 'string',
				default: '',
				description: 'IP restriction.',
			},
			{
				displayName: 'Job Category Id',
				name: 'jobCategoryId',
				type: 'number',
				default: 0,
				description: 'If you require your user to be in a certain group, you can use the Id of the group from the Job Group page to set the default job category.',
			},
			{
				displayName: 'Job Category Description',
				name: 'jobCategoryDescription',
				type: 'string',
				default: '',
				description: 'If you require your user to be in a certain group, you can take the name of the group from the Job Group page to set the default job category.',
			},
			{
				displayName: 'User Type',
				name: 'userType',
				type: 'number',
				default: 0,
				description: 'User license type',
			},
			{
				displayName: 'User Group Description',
				name: 'userGroupDescription',
				type: 'string',
				default: '',
				description: 'If you require your user to be in a certain group, you can input the name of the group from the User Group page, Into this parameter to set the user group',
			},
			{
				displayName: 'User Group Id',
				name: 'userGroupId',
				type: 'number',
				default: 0,
				description: 'If you require your user to be in a certain group, you can take the Id of the group from the User Group page Into this parameter to set the user group',
			},
			{
				displayName: 'User Role Id',
				name: 'userRoleId',
				type: 'number',
				default: 0,
				description: 'If you require your user to have a certain role, you can request Ids from BigChange that you can use to set the user role.',
			},
			{
				displayName: 'User Role Description',
				name: 'userRoleDescription',
				type: 'string',
				default: '',
				description: 'If you’d prefer, you can use the name of the role instead, to set the user role.',
			},
			{
				displayName: 'cust_custom field name',
				name: 'cust_custom field name',
				type: 'string',
				default: '',
				description: 'Pass cust_ followed by the caption of an existing custom field.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebuserlist'],
			},
		},
		options: [
			{
				displayName: 'Return Custom Fields',
				name: 'returnCustomFields',
				type: 'boolean',
				default: false,
				description: 'Include custom fields in the response.',
			},
		],
	},
	{
		displayName: 'Web User Email',
		name: 'webUserEmail',
		type: 'string',
		required: true,
		default: '',
		description: 'User Email Address',
		displayOptions: {
			show: {
				resource: ['wsWebUsers'],
				operation: ['wsWebuserdelete'],
			},
		},
	},
];

export const wsWebUsersRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsWebusersave': { path: '/web-users/webusersave', method: 'post', params: [{"camelName":"webUserName","apiName":"WebUserName","type":"string","default":""},{"camelName":"webUserEmail","apiName":"WebUserEmail","type":"string","default":""},{"camelName":"webUserPwd","apiName":"WebUserPwd","type":"string","default":""},{"camelName":"userMobile","apiName":"UserMobile","type":"string","default":""},{"camelName":"position","apiName":"Position","type":"string","default":""},{"camelName":"userIPRestriction","apiName":"UserIPRestriction","type":"string","default":""},{"camelName":"jobCategoryId","apiName":"JobCategoryId","type":"number","default":0},{"camelName":"jobCategoryDescription","apiName":"JobCategoryDescription","type":"string","default":""},{"camelName":"userType","apiName":"UserType","type":"number","default":0},{"camelName":"userGroupDescription","apiName":"UserGroupDescription","type":"string","default":""},{"camelName":"userGroupId","apiName":"UserGroupId","type":"number","default":0},{"camelName":"userRoleId","apiName":"UserRoleId","type":"number","default":0},{"camelName":"userRoleDescription","apiName":"UserRoleDescription","type":"string","default":""},{"camelName":"cust_custom field name","apiName":"cust_custom field name","type":"string","default":""}] },
	'wsUsergroups': { path: '/web-users/usergroups', method: 'get', params: [] },
	'wsWebuserlist': { path: '/web-users/webuserlist', method: 'get', params: [{"camelName":"returnCustomFields","apiName":"ReturnCustomFields","type":"boolean","default":false}] },
	'wsWebuserdelete': { path: '/web-users/webuserdelete', method: 'post', params: [{"camelName":"webUserEmail","apiName":"WebUserEmail","type":"string","default":""}] },
	'wsUserroles': { path: '/web-users/userroles', method: 'get', params: [] },
};