import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: asset-checks  |  Resource value: wsAssetChecks
// 2 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsAssetChecksOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsAssetChecks'],
			},
		},
		options: [
			{
				name: 'Get an Asset Check',
				value: 'wsGetAnassetcheck',
				action: 'Get an Asset Check via Web Services',
				description: 'This service returns details of a single asset check (vehicle check).',
			},
			{
				name: 'Update a Defect',
				value: 'wsUpdateAdefect',
				action: 'Update a Defect via Web Services',
				description: 'This service allows you to update a defects comment, actioned flag and archived status.',
			},
		],
		default: 'wsGetAnassetcheck',
	},
];

export const wsAssetChecksFields: INodeProperties[] = [
	{
		displayName: 'Check Id',
		name: 'checkId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Integer value returned from an AssetCheck callback service.',
		displayOptions: {
			show: {
				resource: ['wsAssetChecks'],
				operation: ['wsGetAnassetcheck'],
			},
		},
	},
	{
		displayName: 'Defect Id',
		name: 'defectId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the defect which can be retrieved using Defect List.',
		displayOptions: {
			show: {
				resource: ['wsAssetChecks'],
				operation: ['wsUpdateAdefect'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsAssetChecks'],
				operation: ['wsUpdateAdefect'],
			},
		},
		options: [
			{
				displayName: 'Defect Comment',
				name: 'defectComment',
				type: 'string',
				default: '',
				description: 'Adds text passed as a "Comment", on the entity.',
			},
			{
				displayName: 'Mark As Actioned',
				name: 'markAsActioned',
				type: 'boolean',
				default: false,
				description: 'Marks as Actioned. Allowed Values: true, 1, false, 0.',
			},
			{
				displayName: 'Mark As Archived',
				name: 'markAsArchived',
				type: 'boolean',
				default: false,
				description: 'Marks as Archived. Allowed Values: true, 1, false, 0.',
			},
		],
	},
];

export const wsAssetChecksRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsGetAnassetcheck': { path: '/asset-checks/get-anassetcheck', method: 'get', params: [{"camelName":"checkId","apiName":"CheckId","type":"number","default":0}] },
	'wsUpdateAdefect': { path: '/asset-checks/update-adefect', method: 'post', params: [{"camelName":"defectId","apiName":"DefectId","type":"number","default":0},{"camelName":"defectComment","apiName":"DefectComment","type":"string","default":""},{"camelName":"markAsActioned","apiName":"MarkAsActioned","type":"boolean","default":false},{"camelName":"markAsArchived","apiName":"MarkAsArchived","type":"boolean","default":false}] },
};