import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: tracking  |  Resource value: wsTracking
// 4 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsTrackingOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsTracking'],
			},
		},
		options: [
			{
				name: 'Get journey data for a date range',
				value: 'wsJourneys',
				action: 'Get journey data for a date range via Web Services',
				description: 'Retrieve a list of journeys within a specified date range.',
			},
			{
				name: 'Get the last known position of assets',
				value: 'wsLive',
				action: 'Get the last known position of assets via Web Services',
				description: 'Retrieves the latest known position of resources and mobile assets.',
			},
			{
				name: 'Last known odometer readings',
				value: 'wsOdometer',
				action: 'Last known odometer readings via Web Services',
				description: 'This method does not return positional information.',
			},
			{
				name: 'Last known position and odometer',
				value: 'wsLiveodometer',
				action: 'Last known position and odometer via Web Services',
				description: 'This service returns details of Assets last known position and odometer.',
			},
		],
		default: 'wsJourneys',
	},
];

export const wsTrackingFields: INodeProperties[] = [
	{
		displayName: 'Start',
		name: 'start',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'UTC Date and Time you want journey data from. Allowed Values: YYYY-MM-DD',
		displayOptions: {
			show: {
				resource: ['wsTracking'],
				operation: ['wsJourneys'],
			},
		},
	},
	{
		displayName: 'End',
		name: 'end',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'UTC Date and Time you want journey data until.  Allowed Values: YYYY-MM-DD',
		displayOptions: {
			show: {
				resource: ['wsTracking'],
				operation: ['wsJourneys'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTracking'],
				operation: ['wsJourneys'],
			},
		},
		options: [
			{
				displayName: 'Show Idling',
				name: 'showIdling',
				type: 'string',
				default: '',
				description: 'Default is 0.  Set to 1 to include idling information in the response dataset',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTracking'],
				operation: ['wsLiveodometer'],
			},
		},
		options: [
			{
				displayName: 'Asset Registration',
				name: 'assetRegistration',
				type: 'string',
				default: '',
				description: 'The registration number of the asset. If this parameter not provided, the response will  all assets with available data.',
			},
		],
	},
];

export const wsTrackingRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsJourneys': { path: '/tracking/journeys', method: 'get', params: [{"camelName":"start","apiName":"Start","type":"dateTime","default":""},{"camelName":"end","apiName":"End","type":"dateTime","default":""},{"camelName":"showIdling","apiName":"ShowIdling","type":"string","default":""}] },
	'wsLive': { path: '/tracking/live', method: 'get', params: [] },
	'wsOdometer': { path: '/tracking/odometer', method: 'get', params: [] },
	'wsLiveodometer': { path: '/tracking/liveodometer', method: 'get', params: [{"camelName":"assetRegistration","apiName":"AssetRegistration","type":"string","default":""}] },
};
