import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: attachments  |  Resource value: wsAttachments
// 2 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsAttachmentsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsAttachments'],
			},
		},
		options: [
			{
				name: 'List attachments for an entity',
				value: 'wsAttachmentsGetlistofattachments',
				action: 'List attachments for an entity via Web Services',
				description: 'This service lists information about any attachments to the requested entity.',
			},
			{
				name: 'Retrieve an attachment by Id',
				value: 'wsAttachmentsGetanattachment',
				action: 'Retrieve an attachment by Id via Web Services',
				description: 'This service retrieves an attachment using an AttachmentId. This can be retrieved using ListAttachments.',
			},
		],
		default: 'wsAttachmentsGetlistofattachments',
	},
];

export const wsAttachmentsFields: INodeProperties[] = [
	{
		displayName: 'Type',
		name: 'type',
		type: 'string',
		required: true,
		default: '',
		description: 'Attachment Type Name, for example \'job\'.',
		displayOptions: {
			show: {
				resource: ['wsAttachments'],
				operation: ['wsAttachmentsGetlistofattachments'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsAttachments'],
				operation: ['wsAttachmentsGetlistofattachments'],
			},
		},
		options: [
			{
				displayName: 'Entity ID',
				name: 'entityID',
				type: 'string',
				default: '',
				description: 'Entity ID. For example, when using the Contact type, this would be the ContactID. EntityID takes precedence over EntityRef if both parameters are supplied.. Provide either EntityID or EntityRef.',
			},
			{
				displayName: 'Entity Ref',
				name: 'entityRef',
				type: 'string',
				default: '',
				description: 'Entity Reference – for example, when using the Contact Type, this would be the Contact Reference.. Provide either EntityID or EntityRef.',
			},
		],
	},
	{
		displayName: 'Attachment Id',
		name: 'attachmentId',
		type: 'string',
		required: true,
		default: '',
		description: 'The Id of the attachment to be retrieved. Use "ListAttachments" to retrieve document Ids.',
		displayOptions: {
			show: {
				resource: ['wsAttachments'],
				operation: ['wsAttachmentsGetanattachment'],
			},
		},
	},
];

export const wsAttachmentsRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsAttachmentsGetlistofattachments': { path: '/attachments/attachments-getlistofattachments', method: 'get', params: [{"camelName":"type","apiName":"Type","type":"string","default":""},{"camelName":"entityID","apiName":"EntityID","type":"string","default":""},{"camelName":"entityRef","apiName":"EntityRef","type":"string","default":""}] },
	'wsAttachmentsGetanattachment': { path: '/attachments/attachments-getanattachment', method: 'get', params: [{"camelName":"attachmentId","apiName":"AttachmentId","type":"string","default":""}] },
};