import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: messaging  |  Resource value: wsMessaging
// 1 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsMessagingOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsMessaging'],
			},
		},
		options: [
			{
				name: 'Send a device/SMS/email/JobWatch message',
				value: 'wsMessagesend',
				action: 'Send a device/SMS/email/JobWatch message via Web Services',
				description: 'This service enables various types of message to be sent from a single call e.g. send the same message to:.',
			},
		],
		default: 'wsMessagesend',
	},
];

export const wsMessagingFields: INodeProperties[] = [
	{
		displayName: 'Body',
		name: 'body',
		type: 'string',
		required: true,
		default: '',
		description: 'Message body text - Maximum length: 1000',
		displayOptions: {
			show: {
				resource: ['wsMessaging'],
				operation: ['wsMessagesend'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsMessaging'],
				operation: ['wsMessagesend'],
			},
		},
		options: [
			{
				displayName: 'Resource Ids Device',
				name: 'resourceIdsDevice',
				type: 'string',
				default: '',
				description: 'A comma delimited list of resource Ids to send device message to',
			},
			{
				displayName: 'Resource Ids Mobile',
				name: 'resourceIdsMobile',
				type: 'string',
				default: '',
				description: 'A comma delimited list of resource Ids to send SMS to',
			},
			{
				displayName: 'Web User Ids',
				name: 'webUserIds',
				type: 'string',
				default: '',
				description: 'A comma delimited list of user Ids to send JobWatch message to',
			},
			{
				displayName: 'Mobile Numbers',
				name: 'mobileNumbers',
				type: 'string',
				default: '',
				description: 'A comma delimited list of mobile numbers in format +447954012012, to send SMS to (numbers don\'t have to be assigned to a web user)',
			},
			{
				displayName: 'Resource Group Ids',
				name: 'resourceGroupIds',
				type: 'string',
				default: '',
				description: 'A comma delimited list of resource group Ids to send device message to',
			},
			{
				displayName: 'Emails',
				name: 'emails',
				type: 'string',
				default: '',
				description: 'A comma delimited list of email addresses to send email to (don\'t have to be assigned to a web user)',
			},
			{
				displayName: 'All Resources',
				name: 'allResources',
				type: 'boolean',
				default: false,
				description: 'A flag determining if the message is sent to all devices belonging to Resources - Defaults to false',
			},
			{
				displayName: 'Answers',
				name: 'answers',
				type: 'string',
				default: '',
				description: 'A comma delimited list of buttons to show on a device message - e.g. "Yes,No"',
			},
			{
				displayName: 'Subject',
				name: 'subject',
				type: 'string',
				default: '',
				description: 'Subject field of message - Maximum length: 50',
			},
			{
				displayName: 'Thread Id',
				name: 'threadId',
				type: 'number',
				default: 0,
				description: 'Message thread Id',
			},
			{
				displayName: 'Parent Id',
				name: 'parentId',
				type: 'number',
				default: 0,
				description: 'Message parent Id',
			},
			{
				displayName: 'Entity Type',
				name: 'entityType',
				type: 'string',
				default: '',
				description: 'Entity type relating to message - Job = 1, ContactNote = 2',
			},
			{
				displayName: 'Entity Id',
				name: 'entityId',
				type: 'number',
				default: 0,
				description: 'Entity Id relating to message',
			},
			{
				displayName: 'Urgent',
				name: 'urgent',
				type: 'boolean',
				default: false,
				description: 'A flag determining if the message is treated as urgent - Defaults to false',
			},
			{
				displayName: 'Date Time To Send',
				name: 'dateTimeToSend',
				type: 'dateTime',
				default: '',
				description: 'A future UTC date & time to send the message',
			},
		],
	},
];

export const wsMessagingRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsMessagesend': { path: '/messaging/messagesend', method: 'post', params: [{"camelName":"body","apiName":"Body","type":"string","default":""},{"camelName":"resourceIdsDevice","apiName":"ResourceIdsDevice","type":"string","default":""},{"camelName":"resourceIdsMobile","apiName":"ResourceIdsMobile","type":"string","default":""},{"camelName":"webUserIds","apiName":"WebUserIds","type":"string","default":""},{"camelName":"mobileNumbers","apiName":"MobileNumbers","type":"string","default":""},{"camelName":"resourceGroupIds","apiName":"ResourceGroupIds","type":"string","default":""},{"camelName":"emails","apiName":"Emails","type":"string","default":""},{"camelName":"allResources","apiName":"AllResources","type":"boolean","default":false},{"camelName":"answers","apiName":"Answers","type":"string","default":""},{"camelName":"subject","apiName":"Subject","type":"string","default":""},{"camelName":"threadId","apiName":"ThreadId","type":"number","default":0},{"camelName":"parentId","apiName":"ParentId","type":"number","default":0},{"camelName":"entityType","apiName":"EntityType","type":"string","default":""},{"camelName":"entityId","apiName":"EntityId","type":"number","default":0},{"camelName":"urgent","apiName":"Urgent","type":"boolean","default":false},{"camelName":"dateTimeToSend","apiName":"DateTimeToSend","type":"dateTime","default":""}] },
};