import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: tags  |  Resource value: wsTags
// 5 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsTagsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsTags'],
			},
		},
		options: [
			{
				name: 'Add or update a tag',
				value: 'wsSavetag',
				action: 'Add or update a tag via Web Services',
				description: 'Create or update a Tag which can then be later applied to an entity using Add Tag to Data Entity.',
			},
			{
				name: 'Apply a tag to an entity',
				value: 'wsSettag',
				action: 'Apply a tag to an entity via Web Services',
				description: 'Add tags to Jobs, Contact Notes and Sales Opportunities.',
			},
			{
				name: 'Get a list of tags, optionally filtered by Type',
				value: 'wsTags',
				action: 'Get a list of tags, optionally filtered by Type via Web Services',
				description: 'BigChange Web Services Tags: get a list of tags, optionally filtered by Type.',
			},
			{
				name: 'Get tag history',
				value: 'wsTaghistory',
				action: 'Get tag history via Web Services',
				description: 'Retrieves a list of tags assigned to an entity based on the TagEntityTypeId and a list of one or more TagEntityIds. The output includes each tag\'s details.',
			},
			{
				name: 'Remove a tag history entry',
				value: 'wsTaghistorydelete',
				action: 'Remove a tag history entry via Web Services',
				description: 'Deletes a specific tag history entry from various entities, such as jobs, contact notes, contact users, or sales opportunities.',
			},
		],
		default: 'wsSavetag',
	},
];

export const wsTagsFields: INodeProperties[] = [
	{
		displayName: 'Entity Type',
		name: 'entityType',
		type: 'number',
		required: true,
		default: 0,
		description: 'The type of entity associated with the tag.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSavetag'],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: 'The name of the tag.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSavetag'],
			},
		},
	},
	{
		displayName: 'Color',
		name: 'color',
		type: 'string',
		required: true,
		default: '',
		description: 'The name of the color to be assigned to the tag.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSavetag'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'number',
		required: true,
		default: 0,
		description: 'The options associated with the tag.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSavetag'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSavetag'],
			},
		},
		options: [
			{
				displayName: 'Tag Id',
				name: 'tagId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of an existing tag, provided if updating an existing tag.',
			},
		],
	},
	{
		displayName: 'Entity Id',
		name: 'entityId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The identifier of the entity to which the tag is being applied. ie: JobId, ContactNoteId.To apply the tag to multiple entities, provide the parameter multiple times or as a CSV value.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSettag'],
			},
		},
	},
	{
		displayName: 'Tag Id',
		name: 'tagId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the tag being applied. Can be retrieved using Get list of Tags',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSettag'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsSettag'],
			},
		},
		options: [
			{
				displayName: 'Entity Type Id',
				name: 'entityTypeId',
				type: 'string',
				default: '',
				description: 'The type of the identifier of the entity type to which the tag is being applied.',
			},
			{
				displayName: 'Entity Type',
				name: 'entityType',
				type: 'string',
				default: '',
				description: 'The string identifier of the entity type to which the tag is being applied ie Job, ContactNote.Only used if EntityTypeId is not provided.',
			},
			{
				displayName: 'Owner Name',
				name: 'ownerName',
				type: 'string',
				default: '',
				description: 'The name of the person or system responsible for the tag.',
			},
			{
				displayName: 'Comment',
				name: 'comment',
				type: 'string',
				default: '',
				description: 'Additional comments or notes about the tag.',
			},
			{
				displayName: 'Date Time',
				name: 'dateTime',
				type: 'dateTime',
				default: '',
				description: 'The date and time when the tag is applied.',
			},
			{
				displayName: 'Return Type',
				name: 'returnType',
				type: 'string',
				default: '',
				description: 'Specifies the expected return value after applying the tag. Use 0 for no return (default), or 1 to return the EntityId.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsTags'],
			},
		},
		options: [
			{
				displayName: 'Type',
				name: 'type',
				type: 'string',
				default: '',
				description: '',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsTaghistory'],
			},
		},
		options: [
			{
				displayName: 'Tag Entity Type Id',
				name: 'tagEntityTypeId',
				type: 'number',
				default: 0,
				description: 'The ID representing the type of entity whose tag history is being requested.',
			},
			{
				displayName: 'Tag Entity Ids',
				name: 'tagEntityIds',
				type: 'string',
				default: '',
				description: 'A comma-separated list of entity IDs whose tag history you want to retrieve.',
			},
			{
				displayName: 'Change Return',
				name: 'changeReturn',
				type: 'boolean',
				default: false,
				description: 'When set to 1 (true), returns an empty list if no tags are found instead of an error message. The default is 0 (false).',
			},
		],
	},
	{
		displayName: 'Tag History Id',
		name: 'tagHistoryId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the specific tag history entry to delete. The ID can be retrieved using Tag History.',
		displayOptions: {
			show: {
				resource: ['wsTags'],
				operation: ['wsTaghistorydelete'],
			},
		},
	},
];

export const wsTagsRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsSavetag': { path: '/tags/savetag', method: 'post', params: [{"camelName":"entityType","apiName":"EntityType","type":"number","default":0},{"camelName":"name","apiName":"Name","type":"string","default":""},{"camelName":"color","apiName":"Color","type":"string","default":""},{"camelName":"options","apiName":"Options","type":"number","default":0},{"camelName":"tagId","apiName":"TagId","type":"number","default":0}] },
	'wsSettag': { path: '/tags/settag', method: 'post', params: [{"camelName":"entityTypeId","apiName":"EntityTypeId","type":"string","default":""},{"camelName":"entityType","apiName":"EntityType","type":"string","default":""},{"camelName":"entityId","apiName":"EntityId","type":"number","default":0},{"camelName":"tagId","apiName":"TagId","type":"number","default":0},{"camelName":"ownerName","apiName":"OwnerName","type":"string","default":""},{"camelName":"comment","apiName":"Comment","type":"string","default":""},{"camelName":"dateTime","apiName":"DateTime","type":"dateTime","default":""},{"camelName":"returnType","apiName":"ReturnType","type":"string","default":""}] },
	'wsTags': { path: '/tags/tags', method: 'get', params: [{"camelName":"type","apiName":"Type","type":"string","default":""}] },
	'wsTaghistory': { path: '/tags/taghistory', method: 'get', params: [{"camelName":"tagEntityTypeId","apiName":"TagEntityTypeId","type":"number","default":0},{"camelName":"tagEntityIds","apiName":"TagEntityIds","type":"string","default":""},{"camelName":"changeReturn","apiName":"ChangeReturn","type":"boolean","default":false}] },
	'wsTaghistorydelete': { path: '/tags/taghistorydelete', method: 'post', params: [{"camelName":"tagHistoryId","apiName":"TagHistoryId","type":"string","default":""}] },
};