import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: workflow  |  Resource value: wsWorkflow
// 1 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsWorkflowOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsWorkflow'],
			},
		},
		options: [
			{
				name: 'Add a worksheet/workflow answer to a contact note',
				value: 'wsSaveworkflowanswer',
				action: 'Add a worksheet/workflow answer to a contact note via Web Services',
				description: 'Sets the answer to a workflow question on a contact note.',
			},
		],
		default: 'wsSaveworkflowanswer',
	},
];

export const wsWorkflowFields: INodeProperties[] = [
	{
		displayName: 'Question Id',
		name: 'questionId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the worksheet question which can be retrieved using Contact Notes',
		displayOptions: {
			show: {
				resource: ['wsWorkflow'],
				operation: ['wsSaveworkflowanswer'],
			},
		},
	},
	{
		displayName: 'Answer',
		name: 'answer',
		type: 'string',
		required: true,
		default: '',
		description: 'Answer value - E.g.: "True", "3.14", "List item 1".',
		displayOptions: {
			show: {
				resource: ['wsWorkflow'],
				operation: ['wsSaveworkflowanswer'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsWorkflow'],
				operation: ['wsSaveworkflowanswer'],
			},
		},
		options: [
			{
				displayName: 'Contact Note Id',
				name: 'contactNoteId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact note which can be retrieved using Contact Notes.. Provide either ContactNoteId or ContactNoteRef.',
			},
			{
				displayName: 'Contact Note Ref',
				name: 'contactNoteRef',
				type: 'string',
				default: '',
				description: 'The internal reference of the contact note.The Contact Reference or Id can be supplied. If both parameters are provided, the Contact Id will take precedence.. Provide either ContactNoteId or ContactNoteRef.',
			},
			{
				displayName: 'Note',
				name: 'note',
				type: 'string',
				default: '',
				description: 'Comments or notes on the answer - Applicable to all answer types.',
			},
			{
				displayName: 'Quantity',
				name: 'quantity',
				type: 'number',
				default: 0,
				description: 'Quantity value.',
			},
			{
				displayName: 'Excl Tax',
				name: 'exclTax',
				type: 'number',
				default: 0,
				description: '',
			},
			{
				displayName: 'Vat',
				name: 'vat',
				type: 'number',
				default: 0,
				description: '',
			},
			{
				displayName: 'Inc Tax',
				name: 'incTax',
				type: 'number',
				default: 0,
				description: '',
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: '',
				description: '',
			},
			{
				displayName: 'Excl Tax *',
				name: 'exclTax *',
				type: 'string',
				default: '',
				description: 'Cost value - Either IncTax or ExclTax should be specified.',
			},
			{
				displayName: 'Vat *',
				name: 'vat *',
				type: 'string',
				default: '',
				description: 'Tax as a percentage of the cost IncTax.',
			},
			{
				displayName: 'Inc Tax *',
				name: 'incTax *',
				type: 'string',
				default: '',
				description: 'Cost value - Either IncTax or ExclTax should be specified.',
			},
			{
				displayName: 'Currency *',
				name: 'currency *',
				type: 'string',
				default: '',
				description: 'ISO 3 character currency identifier - E.g.: "GBP" "USD" "EUR".',
			},
		],
	},
];

export const wsWorkflowRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsSaveworkflowanswer': { path: '/workflow/saveworkflowanswer', method: 'post', params: [{"camelName":"questionId","apiName":"QuestionId","type":"number","default":0},{"camelName":"contactNoteId","apiName":"ContactNoteId","type":"number","default":0},{"camelName":"contactNoteRef","apiName":"ContactNoteRef","type":"string","default":""},{"camelName":"answer","apiName":"Answer","type":"string","default":""},{"camelName":"note","apiName":"Note","type":"string","default":""},{"camelName":"quantity","apiName":"Quantity","type":"number","default":0},{"camelName":"exclTax","apiName":"ExclTax","type":"number","default":0},{"camelName":"vat","apiName":"Vat","type":"number","default":0},{"camelName":"incTax","apiName":"IncTax","type":"number","default":0},{"camelName":"currency","apiName":"Currency","type":"string","default":""},{"camelName":"exclTax *","apiName":"ExclTax *","type":"string","default":""},{"camelName":"vat *","apiName":"Vat *","type":"string","default":""},{"camelName":"incTax *","apiName":"IncTax *","type":"string","default":""},{"camelName":"currency *","apiName":"Currency *","type":"string","default":""}] },
};