import type { INodeProperties } from 'n8n-workflow';

// Generated by scripts/generate-webservices-descriptions.mjs
// Tag: contact-notes  |  Resource value: wsContactNotes
// 9 operations generated (standalone).
// Re-run the generator to pick up new OpenAPI operations; do not hand-edit.

export const wsContactNotesOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
			},
		},
		options: [
			{
				name: 'Contact Note Delete',
				value: 'wsContactnoteDelete',
				action: 'Contact Note Delete via Web Services',
				description: 'This web service allows you to remove contact notes using a contact note Id.',
			},
			{
				name: 'Contact Note Parent Link',
				value: 'wsContactnoteParentlink',
				action: 'Contact Note Parent Link via Web Services',
				description: 'This allows you to link a contact note to a parent contact note, using the contact note Id, and the Id of the parent note.',
			},
			{
				name: 'Contact Note Priorities',
				value: 'wsContactnotePriorities',
				action: 'Contact Note Priorities via Web Services',
				description: 'Get contact note priorities.',
			},
			{
				name: 'Contact Note Save',
				value: 'wsContactnoteSave',
				action: 'Contact Note Save via Web Services',
				description: 'Add or update a contact note.',
			},
			{
				name: 'Contact Note Type List',
				value: 'wsContactnoteTypelist',
				action: 'Contact Note Type List via Web Services',
				description: 'This service returns a list of all note types available for the current user. Each entry will show Name and Id.',
			},
			{
				name: 'Contact Notes',
				value: 'wsContactnotes',
				action: 'Contact Notes via Web Services',
				description: 'This web service allows you to retrieve the contact notes by Id or reference.',
			},
			{
				name: 'Contact Notes By Parent',
				value: 'wsContactnoteByparentcontact',
				action: 'Contact Notes By Parent via Web Services',
				description: 'Retrieve a list of contact notes that have the supplied contact as a parent of the notes contact.',
			},
			{
				name: 'Contact Save Note Type',
				value: 'wsContactsavenotetype',
				action: 'Contact Save Note Type via Web Services',
				description: 'Add or update a contact note type.',
			},
			{
				name: 'Get Contact Note',
				value: 'wsGetcontactnote',
				action: 'Get Contact Note via Web Services',
				description: 'Get a contact note.',
			},
		],
		default: 'wsContactnoteDelete',
	},
];

export const wsContactNotesFields: INodeProperties[] = [
	{
		displayName: 'Contact Note Id',
		name: 'contactNoteId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the contact note which can be retrieved using Contact Notes.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteDelete'],
			},
		},
	},
	{
		displayName: 'Contact Note Id',
		name: 'contactNoteId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the contact note which can be retrieved using Contact Notes.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteParentlink'],
			},
		},
	},
	{
		displayName: 'Contact Note Parent Id',
		name: 'contactNoteParentId',
		type: 'number',
		required: true,
		default: 0,
		description: 'The unique identifier of the contact note which can be retrieved using Contact Notes.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteParentlink'],
			},
		},
	},
	{
		displayName: 'Overwrite If Exists',
		name: 'overwriteIfExists',
		type: 'boolean',
		required: true,
		default: false,
		description: 'Set to \'true\' to overwrite an existing parent note link, or or \'false\'.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteParentlink'],
			},
		},
	},
	{
		displayName: 'Note Type Id',
		name: 'noteTypeId',
		type: 'number',
		required: true,
		default: 0,
		description: 'Unique Id of the note type.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteSave'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteSave'],
			},
		},
		options: [
			{
				displayName: 'Contact Id',
				name: 'contactId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact which can be retrieved using Contact List.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Contact Ref',
				name: 'contactRef',
				type: 'string',
				default: '',
				description: 'The internal reference of the contact.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Worksheet Id',
				name: 'worksheetId',
				type: 'string',
				default: '',
				description: 'Unique Id of the worksheet.',
			},
			{
				displayName: 'Owner Id',
				name: 'ownerId',
				type: 'string',
				default: '',
				description: 'Unique Id of the owner.',
			},
			{
				displayName: 'Subject',
				name: 'subject',
				type: 'string',
				default: '',
				description: 'Text for the note\'s Subject field.',
			},
			{
				displayName: 'Note Text',
				name: 'noteText',
				type: 'string',
				default: '',
				description: 'Text for the note\'s Notes field.',
			},
			{
				displayName: 'Note Completion Text',
				name: 'noteCompletionText',
				type: 'string',
				default: '',
				description: 'Text for the note\'s Completion Details field (only for \'Completed\' notes).',
			},
			{
				displayName: 'Due Date',
				name: 'dueDate',
				type: 'dateTime',
				default: '',
				description: '\'Due date\' date and time.',
			},
			{
				displayName: 'Days To Add',
				name: 'daysToAdd',
				type: 'number',
				default: 0,
				description: 'If set adds number of days to DueDate. If no DueDate set and DaysToAdd sent the days to add will be added from current datetime.',
			},
			{
				displayName: 'Reference',
				name: 'reference',
				type: 'string',
				default: '',
				description: 'Specifies contact note reference.',
			},
			{
				displayName: 'Reference Postfix',
				name: 'referencePostfix',
				type: 'string',
				default: '',
				description: 'If set adds String to end of reference.',
			},
			{
				displayName: 'Contact Note Status',
				name: 'contactNoteStatus',
				type: 'string',
				default: '',
				description: 'Options: "Open", "Completed" or "Cancelled"',
			},
			{
				displayName: 'cust_custom field name',
				name: 'cust_custom field name',
				type: 'string',
				default: '',
				description: 'Pass cust_ followed by the caption of an existing custom field.',
			},
		],
	},
	{
		displayName: 'Error On None Found',
		name: 'errorOnNoneFound',
		type: 'boolean',
		required: true,
		default: false,
		description: 'If you would like an error message where there are no contact note types. 1 = do not show error, 0 = show errors.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteTypelist'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnotes'],
			},
		},
		options: [
			{
				displayName: 'Contact Id',
				name: 'contactId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact which can be retrieved using Contact List.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Contact Ref',
				name: 'contactRef',
				type: 'string',
				default: '',
				description: 'The internal reference of the contact.. Provide either ContactId or ContactRef.',
			},
			{
				displayName: 'Flag History',
				name: 'flagHistory',
				type: 'string',
				default: '',
				description: 'Include tags in the response.',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'includeCustomFields',
				type: 'boolean',
				default: false,
				description: 'Include custom fields in the response.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactnoteByparentcontact'],
			},
		},
		options: [
			{
				displayName: 'Contact Id',
				name: 'contactId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact which can be retrieved using Contact List.. Provide either ContactId or ContactReference.',
			},
			{
				displayName: 'Contact Reference',
				name: 'contactReference',
				type: 'string',
				default: '',
				description: 'The internal reference of the contact.. Provide either ContactId or ContactReference.',
			},
			{
				displayName: 'Date From',
				name: 'dateFrom',
				type: 'dateTime',
				default: '',
				description: 'Filter by Creation Date, Format: yyyy-MM-dd HH:mm:ss',
			},
			{
				displayName: 'Date To',
				name: 'dateTo',
				type: 'dateTime',
				default: '',
				description: 'Filter by Creation Date, Format: yyyy-MM-dd HH:mm:ss',
			},
		],
	},
	{
		displayName: 'Note Type Name',
		name: 'noteTypeName',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of note type.',
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactsavenotetype'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsContactsavenotetype'],
			},
		},
		options: [
			{
				displayName: 'Status New Email',
				name: 'statusNewEmail',
				type: 'number',
				default: 0,
				description: 'Email address for \'When note is created\'.',
			},
			{
				displayName: 'Status Complete Email',
				name: 'statusCompleteEmail',
				type: 'number',
				default: 0,
				description: 'Email address for \'When note is completed\'.',
			},
			{
				displayName: 'Status New Email Letter Id',
				name: 'statusNewEmailLetterId',
				type: 'number',
				default: 0,
				description: 'Unique Id of letter template for status New email.',
			},
			{
				displayName: 'Status Complete Email Letter Id',
				name: 'statusCompleteEmailLetterId',
				type: 'number',
				default: 0,
				description: 'Unique Id of letter template for status Completed email.',
			},
			{
				displayName: 'Associated Worksheet Ids',
				name: 'associatedWorksheetIds',
				type: 'string',
				default: '',
				description: 'Unique Id of worksheet to set as \'Default workflow.\'',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['wsContactNotes'],
				operation: ['wsGetcontactnote'],
			},
		},
		options: [
			{
				displayName: 'Contact Note Id',
				name: 'contactNoteId',
				type: 'number',
				default: 0,
				description: 'The unique identifier of the contact note which can be retrieved using Contact Notes.. Provide either ContactNoteId or ContactNoteRef.',
			},
			{
				displayName: 'Contact Note Ref',
				name: 'contactNoteRef',
				type: 'string',
				default: '',
				description: 'The internal reference of the contact note.. Provide either ContactNoteId or ContactNoteRef.',
			},
		],
	},
];

export const wsContactNotesRoutes: Record<string, {
	path: string;
	method: string;
	params: Array<{ camelName: string; apiName: string; type: string; default: string | number | boolean }>;
}> = {
	'wsContactnoteDelete': { path: '/contact-notes/contactnote-delete', method: 'post', params: [{"camelName":"contactNoteId","apiName":"ContactNoteId","type":"number","default":0}] },
	'wsContactnoteParentlink': { path: '/contact-notes/contactnote-parentlink', method: 'post', params: [{"camelName":"contactNoteId","apiName":"ContactNoteId","type":"number","default":0},{"camelName":"contactNoteParentId","apiName":"ContactNoteParentId","type":"number","default":0},{"camelName":"overwriteIfExists","apiName":"OverwriteIfExists","type":"boolean","default":false}] },
	'wsContactnotePriorities': { path: '/contact-notes/contactnote-priorities', method: 'get', params: [] },
	'wsContactnoteSave': { path: '/contact-notes/contactnote-save', method: 'post', params: [{"camelName":"contactId","apiName":"ContactId","type":"number","default":0},{"camelName":"contactRef","apiName":"ContactRef","type":"string","default":""},{"camelName":"noteTypeId","apiName":"NoteTypeId","type":"number","default":0},{"camelName":"worksheetId","apiName":"WorksheetId","type":"string","default":""},{"camelName":"ownerId","apiName":"OwnerId","type":"string","default":""},{"camelName":"subject","apiName":"Subject","type":"string","default":""},{"camelName":"noteText","apiName":"NoteText","type":"string","default":""},{"camelName":"noteCompletionText","apiName":"NoteCompletionText","type":"string","default":""},{"camelName":"dueDate","apiName":"DueDate","type":"dateTime","default":""},{"camelName":"daysToAdd","apiName":"DaysToAdd","type":"number","default":0},{"camelName":"reference","apiName":"Reference","type":"string","default":""},{"camelName":"referencePostfix","apiName":"ReferencePostfix","type":"string","default":""},{"camelName":"contactNoteStatus","apiName":"ContactNoteStatus","type":"string","default":""},{"camelName":"cust_custom field name","apiName":"cust_custom field name","type":"string","default":""}] },
	'wsContactnoteTypelist': { path: '/contact-notes/contactnote-typelist', method: 'get', params: [{"camelName":"errorOnNoneFound","apiName":"ErrorOnNoneFound","type":"boolean","default":false}] },
	'wsContactnotes': { path: '/contact-notes/contactnotes', method: 'get', params: [{"camelName":"contactId","apiName":"ContactId","type":"number","default":0},{"camelName":"contactRef","apiName":"ContactRef","type":"string","default":""},{"camelName":"flagHistory","apiName":"FlagHistory","type":"string","default":""},{"camelName":"includeCustomFields","apiName":"IncludeCustomFields","type":"boolean","default":false}] },
	'wsContactnoteByparentcontact': { path: '/contact-notes/contactnote-byparentcontact', method: 'get', params: [{"camelName":"contactId","apiName":"ContactId","type":"number","default":0},{"camelName":"contactReference","apiName":"ContactReference","type":"string","default":""},{"camelName":"dateFrom","apiName":"DateFrom","type":"dateTime","default":""},{"camelName":"dateTo","apiName":"DateTo","type":"dateTime","default":""}] },
	'wsContactsavenotetype': { path: '/contact-notes/contactsavenotetype', method: 'post', params: [{"camelName":"noteTypeName","apiName":"NoteTypeName","type":"string","default":""},{"camelName":"statusNewEmail","apiName":"StatusNewEmail","type":"number","default":0},{"camelName":"statusCompleteEmail","apiName":"StatusCompleteEmail","type":"number","default":0},{"camelName":"statusNewEmailLetterId","apiName":"StatusNewEmailLetterId","type":"number","default":0},{"camelName":"statusCompleteEmailLetterId","apiName":"StatusCompleteEmailLetterId","type":"number","default":0},{"camelName":"associatedWorksheetIds","apiName":"AssociatedWorksheetIds","type":"string","default":""}] },
	'wsGetcontactnote': { path: '/contact-notes/getcontactnote', method: 'get', params: [{"camelName":"contactNoteId","apiName":"ContactNoteId","type":"number","default":0},{"camelName":"contactNoteRef","apiName":"ContactNoteRef","type":"string","default":""}] },
};